##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.bash.base AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "bash"
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="rest" \
    CONTECO_NAME="base" \
    CONTECO_TAG="v1.0.3" \
    CONTECO_BASE="bash.base" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="rest" \
      io.vcweb.name="base" \
      io.vcweb.tag="v1.0.3" \
      io.vcweb.base="bash.base" \
      io.vcweb.build="image-base" \
      io.vcweb.label="rest.base - Conteco" \
      io.vcweb.description="ContEco REST base image for InfoMetis REST API client implementations, providing the base functionality using curl." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.rest.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
